config/routes.rb
Rails.application.routes.draw do
  
  resources :appointments
  # consider substituting the below lines with resources
  #get '/home/appointment/index'
  #get '/home/:id/appointment/new', to: "appointment#new"
  #get 'appointment/edit'

  # devise_for :patients We commented this, because we are going to redefine our routes according to our new controller Patients
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # This is to redefine the default routes and give it the new naming and routing with our new devise controllers 
  devise_for :patients, controllers: { registrations: 'patients/registrations',
    sessions: 'patients/sessions', unlocks: 'patients/unlocks',
    passwords: 'patients/passwords', confirmations: 'patients/confirmations'}


  # resources :patients do
  #     resources :appointments
  # end

  get "/home", to: "home#index", as: "home"


  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :authenticate_patient!
    def index
        @patient = current_patient
        #puts "HEY PATIENT"
        #puts @patient.appointments
        @apt = @patient.appointments # grabbing all appts for this patient
        #puts patient_session
    end




end

app/views/home/index.html.erb
<h1>Welcome <%= @patient.name %></h1>
<h3>MRN: <%= @patient.id%></h3>

<h3>Patient Health Record</h3>
  
    <% if @patient.gender == 0 %>
            <p>Gender: Male</p>
        <% else  %>
            <p>Gender: Female</p>
    <%end%>

    <p>Age: <%= @patient.age%> years</p>
    <p>Blood Type: <%= @patient.blood_type%></p>
    <p>Allergies: <%= @patient.allergies%></p>
    <p>Weight: <%= @patient.weight%> kg</p>
    <p>Height: <%= @patient.height%> cm</p>
    <p>Body Mass Index: <%= '%02d' % (@patient.weight/(((@patient.height)/100)*2))%></p>
<hr>


    <h3> Patient Appointments </h3>
    <% @apt.each do |apt|%>
        <p> Appt number: <%= apt.id%> </p>
        <p> Clinic Type: <%= apt.clinic%> </p>
        <p> Date: <%= apt.date%> </p>
        <p> Time: <%= apt.time.to_s[11, 5]%> </p>
    <%= link_to "Cancel", appointment_path(apt.id), method: :delete%> || <%= link_to "Reschedule", edit_appointment_path(apt.id)%>
    <hr>
    <% end %>


<%= link_to "Book New Appt", new_appointment_path%><br>
<%= link_to "Sign Out", destroy_patient_session_path, method: :delete%>